# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanstats',
            name='funded_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
